apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: argocd-demo
 namespace: argocd
spec:
 syncPolicy:
  automated: {}
 project: default
 source:
  repoURL: https://github.com/zele26/argocd-demo.git
  targetRevision: HEAD
  path: .
 destination:
  server: https://kubernetes.default.svc
  namespace: default
