apiVersion: apps/v1
kind: Deploymen
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
